### ISSUE TITLE
?

### ISSUE THREAD

**Issue by mloso** [Korol-tvoego-serde4ka/TemperamentTest#1]
Как дизлайк поставить?

**Comment by Korol-tvoego-serde4ka** [comment]
Это мой первый код, если можешь исправить, то я только ЗА! В описании также написано, что код мягко говоря не очень)

**Comment by Korol-tvoego-serde4ka** [comment]
> Как дизлайк поставить?

Используйте этот комментарий, как дизлайк)

**Comment by Korol-tvoego-serde4ka** [comment]
И вообще, зато сам написал, без копипасты👍

**Comment by mloso** [comment]
> Это мой первый код, если можешь исправить, то я только ЗА! В описании также написано, что код мягко говоря не очень)

А, точно)
